const DREAM_APP_WELCOME_REQUEST = 'DREAM_APP_WELCOME_REQUEST';
const DREAM_APP_WELCOME_REQUEST_SUCCESS = 'DREAM_APP_WELCOME_REQUEST_SUCCESS';
const DREAM_APP_WELCOME_REQUEST_FAIL = 'DREAM_APP_WELCOME_REQUEST_FAIL';

const DreamAppWelcomeActionTypes = {
  DREAM_APP_WELCOME_REQUEST,
  DREAM_APP_WELCOME_REQUEST_SUCCESS,
  DREAM_APP_WELCOME_REQUEST_FAIL,
};

export default DreamAppWelcomeActionTypes;
